chore(actions): Add error message when fail occurs

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -40,4 +40,6 @@ jobs:
 
       - name: Check if ansible_lint step has failed
         if: steps.ansible_lint.outcome == 'failure'
-        run: exit 1
+        run: |
+          echo "::error title=Ansible-lint::Error during the ansible-lint step"
+          exit 1
