chore(actions): Fail even if code change has side-effects (#36)
Test if it fixes the problem raised in #32

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -28,6 +28,7 @@ jobs:
           echo "VIRTUAL_ENV=$(pwd)/.venv" >> "${GITHUB_ENV}"
 
       - name: Run Ansible-Lint
+        id: ansible_lint
         continue-on-error: true # Allow uploading SARIF report if ansible-lint is not happy
         run: ansible-lint --offline --sarif-file ansible-lint.sarif.json # TODO: Reuse just lint
 
@@ -36,3 +37,9 @@ jobs:
         with:
           sarif_file: ansible-lint.sarif.json
           category: ansible-lint
+
+      - name: Check if ansible_lint step has failed
+        if: steps.ansible_lint.outcome == 'failure'
+        run: |
+          echo "::error title=Ansible-lint::Error during the ansible-lint step"
+          exit 1
